@API_HostAddress = http://localhost:5000/api/events

#Get Event
GET {{API_HostAddress}}/f48cb999-121c-429c-82fa-72bbaefbc516
Accept: application/json
Content-Type: application/json

###

#Get Event list
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

###

#Get Event list by Venue
GET {{API_HostAddress}}?venue=32eb4144-50d7-40b0-9ed0-417a02a0c82b
Accept: application/json
Content-Type: application/json

###


# Create Event
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "title": "Event 20",
  "description": "Event 20 description",
  "dateTime": "2024-10-20T21:00",
  "venueId": "531f0074-6e6a-4954-8ad9-55a4d4b20220"
}
###


#Edit Event
PUT {{API_HostAddress}}/f48cb999-121c-429c-82fa-72bbaefbc516
Accept: application/json
Content-Type: application/json

{
  "title": "Necc Party New",
  "description": "Necc Party description",
  "dateTime": "2024-09-23T21:00",
  "venueId": "32eb4144-50d7-40b0-9ed0-417a02a0c82b"
}
###


# Delete Event
DELETE {{API_HostAddress}}/4cad48f4-31e2-407a-ac83-dd1b6aef601d
Accept: application/json
Content-Type: application/json

###
