@API_HostAddress = http://localhost:5000/api/events
@API_HostAddressLogin = http://localhost:5000/api/accounts


# Login
# @name postLogin
POST {{API_HostAddressLogin}}
Accept: application/json
Content-Type: application/json

{
  "email": "cs@cs.cs",
  "password": "Password1"
}
###
@token = {{postLogin.response.body.data.token}}


#Get Event
GET {{API_HostAddress}}/cd8ac7a3-8ade-4068-9ee6-5a509a1cfc0f
Accept: application/json
Content-Type: application/json

###

#Get Event list
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

###

#Get Event list by Venue
GET {{API_HostAddress}}?venue=4E5FA185-73DE-449A-BB58-4C9A51D0AD45
Accept: application/json
Content-Type: application/json

###


# Create Event
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Create test",
  "description": "Create event test",
  "dateTime": "2024-10-20T21:00",
  "venueId": "531f0074-6e6a-4954-8ad9-55a4d4b20220"
}
###


#Edit Event
PUT {{API_HostAddress}}/f48cb999-121c-429c-82fa-72bbaefbc516
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Necc Party New 1",
  "description": "Necc Party description",
  "dateTime": "2024-09-23T21:00",
  "venueId": "32eb4144-50d7-40b0-9ed0-417a02a0c82b"
}
###


# Delete Event
DELETE {{API_HostAddress}}/13fa8fa9-eed0-46a6-87d2-6582f62b2f1b
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
