@API_HostAddress = http://localhost:5000/api/tickets
@API_HostAddressLogin = http://localhost:5000/api/accounts


# Login
# @name postLogin
POST {{API_HostAddressLogin}}
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.hu",
  "password": "Password1"
}
###
@accessToken = {{postLogin.response.body.data.accessToken}}


# Create Ticket
POST {{API_HostAddress}}/52a1fd5a-569b-40e5-bdf1-4bf714cfbe70
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "price": 6000,
    "quantity": 3,
    "status" : "AVAILABLE"
}