@API_HostAddress = http://localhost:5000/api/tickets
@API_HostAddressLogin = http://localhost:5000/api/accounts


# Login
# @name postLogin
POST {{API_HostAddressLogin}}
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.hu",
  "password": "Password1"
}
###
@accessToken = {{postLogin.response.body.data.accessToken}}


# Create Ticket
POST {{API_HostAddress}}/3f6599ab-1cbf-438b-b1ec-c046a835bb6f
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "price": 10000,
    "quantity": 20,
    "status" : "AVAILABLE"
}
###

# Get Tickets of an event for Admin
GET {{API_HostAddress}}/admin/3f6599ab-1cbf-438b-b1ec-c046a835bb6f
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# Get Tickets of an event
GET {{API_HostAddress}}/3f6599ab-1cbf-438b-b1ec-c046a835bb6f
Accept: application/json
Content-Type: application/json

###
