@API_HostAddress = http://localhost:5000/api/venues
@API_HostAddressLogin = http://localhost:5000/api/accounts

# Login
# @name postLogin
POST {{API_HostAddressLogin}}
Accept: application/json
Content-Type: application/json

{
  "email": "cs@cs.cs",
  "password": "Password1"
}
###
@token = {{postLogin.response.body.token}}


#Get Venue
GET {{API_HostAddress}}/4E5FA185-73DE-449A-BB58-4C9A51D0AD45
Accept: application/json
Content-Type: application/json

###


#Get Venue list
GET {{API_HostAddress}}?pagenumber=0&pagesize=10
Accept: application/json
Content-Type: application/json

###


#Edit Venue
PUT {{API_HostAddress}}/A11B1817-4AEA-4032-8995-86BB2FD13D62
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mátyás-templom edited",
  "description": "Mátyás-templom edited",
  "address": {
    "country": "Magyarország",
    "zipCode": "1024",
    "city": "Budapest",
    "street": "Szentháromság tér 2."
  }
}
###


# Create Venue
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Magyar Állami Operaház 4",
  "description": "Magyar Állami Operaház",
  "address": {
    "country": "Magyarország",
    "zipCode": "1083",
    "city": "Budapest",
    "street": "Orczy út 14."
  }
}
###


# Delete Venue
DELETE {{API_HostAddress}}/4E5FA185-73DE-449A-BB58-4C9A51D0AD45
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
