@API_HostAddress = http://localhost:5000/api/venues
@API_HostAddressLogin = http://localhost:5000/api/accounts

# Login
# @name postLogin
POST {{API_HostAddressLogin}}
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.hu",
  "password": "Password1"
}
###
@accessToken = {{postLogin.response.body.data.accessToken}}

#Get Venue
GET {{API_HostAddress}}/092BF2CE-2870-4DA3-A898-8F5BEE976E8C
Accept: application/json
Content-Type: application/json

###


#Get Venue list
GET {{API_HostAddress}}?pagenumber=0&pagesize=10&name=magy
Accept: application/json
Content-Type: application/json

###


#Edit Venue
PUT {{API_HostAddress}}/95CB366B-4669-4126-8143-A5AEE1DA96FF
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Magyar Állami Operaház 51",
  "description": "Magyar Állami Operahá",
  "address": {
    "country": "Magyarország",
    "zipCode": "1024",
    "city": "Budapest",
    "street": "Szentháromság tér 2."
  }
}
###


# Create Venue
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Magyar Állami Operaház 5",
  "description": "Magyar Állami Operaház",
  "address": {
    "country": "Magyarország",
    "zipCode": "1083",
    "city": "Budapest",
    "street": "Orczy út 14."
  }
}
###


# Delete Venue
DELETE {{API_HostAddress}}/5CA10D92-D641-4324-B6E8-742582AC5023
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
