@API_HostAddress = http://localhost:5000/api/venues

#Get Venue
GET {{API_HostAddress}}/A11B1817-4AEA-4032-8995-86BB2FD13D62
Accept: application/json
Content-Type: application/json

###


#Get Venue list
GET {{API_HostAddress}}?pagenumber=0&pagesize=10
Accept: application/json
Content-Type: application/json

###


#Edit Venue
PUT {{API_HostAddress}}/A11B1817-4AEA-4032-8995-86BB2FD13D62
Accept: application/json
Content-Type: application/json

{
  "name": "Mátyás-templom edited",
  "description": "Mátyás-templom edited",
  "address": {
    "country": "Magyarország",
    "zipCode": "1024",
    "city": "Budapest",
    "street": "Szentháromság tér 2."
  }
}
###


# Create Venue
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "name": "Magyar Állami Operaház 3",
  "description": "Magyar Állami Operaház",
  "address": {
    "country": "Magyarország",
    "zipCode": "1083",
    "city": "Budapest",
    "street": "Orczy út 14."
  }
}
###


# Delete Venue
DELETE {{API_HostAddress}}/29c9da2c-320c-46cd-901a-669228614aa3
Accept: application/json
Content-Type: application/json

###
